name: composite
on:
  workflow_dispatch:
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
    - uses: jglick/composite-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out
      uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jglick/composite-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
