# work around https://github.com/cli/cli/issues/1316#issuecomment-748674669
name: create-check
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Check name'
        required: true
        default: test
      status:
        description: 'pending / success / failure'
        required: true
        default: pending
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        sha=$(gh api /repos/$GITHUB_REPOSITORY/branches/main | jq -r .commit.sha)
        if [ $INPUT_STATUS = pending ]
        then
            gh api -Fname=test -Fhead_sha=$sha -Fstatus=in_progress /repos/$GITHUB_REPOSITORY/check-runs
        else
            gh api -Fname=test -Fhead_sha=$sha -Fconclusion=$INPUT_STATUS /repos/$GITHUB_REPOSITORY/check-runs
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
