name: release
on:
  workflow_dispatch:
  status:
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: test
      run: |
        state=$(jq -r .state < $GITHUB_EVENT_PATH)
        context=$(jq -r .context < $GITHUB_EVENT_PATH)
        echo received $GITHUB_EVENT_NAME on $GITHUB_SHA state=$state context=$context
        if [ $GITHUB_EVENT_NAME = status -a $state = success -a $context = ci/official ]
        then
          echo proceed
        else
          echo abort
        fi
