name: release
on:
  workflow_dispatch:
  status:
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: check
      run: |
        if [ $GITHUB_EVENT_NAME = status ]
        then
          state=$(jq -r .state < $GITHUB_EVENT_PATH)
          context=$(jq -r .context < $GITHUB_EVENT_PATH)
          if [ $state = success -a $context = ci/official ]
          then
            echo passing
          else
            echo not passing
            exit 1
          fi
        elif [ $GITHUB_EVENT_NAME = workflow_dispatch ]
        then
          if curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -s $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/statuses | jq -e '.[] | select(.context == "ci/official" and .state == "success")'
          then
            echo passing
          else
            echo not passing
            exit 1
          fi
        else
          echo unknown event type $GITHUB_EVENT_NAME
          exit 1
        fi
    - name: Check out
      uses: actions/checkout@v1
    - name: Release
      run: ls -l
