name: release
on:
  workflow_dispatch:
  status:
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: test
      run: |
        echo received $GITHUB_EVENT_NAME on $GITHUB_SHA
        cat $GITHUB_EVENT_PATH
