name: Stuff
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -i https://api.github.com/user
          curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -i https://api.github.com/installation/repositories
