name: Stuff
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check installation token
        run: |
          curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/installation/repositories | jq -r '.repositories[0].full_name'
          TAG=permcheck-$RANDOM; \
            curl -i -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -d '{"ref":"refs/tags/'$TAG'","sha":"'$GITHUB_SHA'"}' https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs; \
            curl -i -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs/tags/$TAG
